[build]
  command = "npm run build:netlify"
  publish = "build"
  environment = { SECRETS_SCAN_OMIT_KEYS = "REACT_APP_API_BASE_URL,REACT_APP_GOOGLE_CLIENT_ID,REACT_APP_GA_ID" }

[[redirects]]
  from = "/podcast.html"
  to = "/"
  status = 200
