[build]
  command = "npm run build:netlify"
  publish = "build"
  environment = { SECRETS_SCAN_OMIT_KEYS = "REACT_APP_API_BASE_URL,REACT_APP_GOOGLE_CLIENT_ID,REACT_APP_GA_ID,REACT_APP_OPENROUTER_API_KEY" }

# Security headers with OAuth support
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # CSP that allows Google OAuth and Facebook OAuth
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com https://accounts.google.com https://connect.facebook.net https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://*.supabase.co https://api.openrouter.ai https://search.brave.com https://accounts.google.com https://graph.facebook.com https://www.google-analytics.com https://osbackend-zl1h.onrender.com;
      frame-src 'self' https://accounts.google.com https://www.facebook.com https://www.youtube.com;
      frame-ancestors 'self';
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://accounts.google.com https://www.facebook.com;
    """

# Handle SPA routing - all routes should be handled by React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/podcast.html"
  to = "/"
  status = 200

[[redirects]]
  from = "/login.html"
  to = "/login"
  status = 200

[[redirects]]
  from = "/signup.html"
  to = "/signup"
  status = 200

[[redirects]]
  from = "/admin-analytics.html"
  to = "/admin-analytics"
  status = 200
